#docker run --name mysql-database -p 3300:3306 -d  -v C:\Users\BrockLaptop\Desktop\Projects\go\api\sql\data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=123456 -e MYSQL_DATABASE=go_admin  mysql


FROM mysql:latest