#docker run --name mysql-database -it -v C:\Users\BrockLaptop\Desktop\Projects\go\api\sql\data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=$$B@ckspace1!! -e MYSQL_DATABASE=go_admin -p 3006:3006 mysql:latest bash


FROM mysql:latest